# Site settings
title: derw
email:
description: dew's webzone
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://derw.pw" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
