# Site settings
title: Derw
email: your-email@domain.com
description: dew's webzone
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://derw.pw" # the base hostname & protocol for your site

# Social links
social: {
    twitter: 'https://twitter.com/notderw',
    github:  'https://github.com/notderw'
}

# Build settings
markdown: kramdown
